name: simlab-app

include:
  - ./infrastructure.yaml

services:
  backend:
    build: ./webapp/backend
    container_name: backend
    environment:
      - FLASK_APP=app.py
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5001
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    networks:
      - simlab_net

  frontend:
    build: ./webapp/frontend
    container_name: frontend
    volumes:
      - ./nginx/ssl:/certs
    depends_on:
      - backend
    networks:
      - simlab_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - simlab_net
    depends_on:
      - registry
      - backend
      - frontend
