version: '3'
name: simlab-project

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - auth_net

  backend:
    build: ./webapp/backend
    container_name: backend
    environment:
      - FLASK_APP=app.py
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5001
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    networks:
      - auth_net

  frontend:
    build: ./webapp/frontend
    container_name: frontend
    volumes:
      - ./nginx/ssl:/certs
    depends_on:
      - backend
    networks:
      - auth_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - auth_net
    depends_on:
      - registry
      - backend
      - frontend

  registry:
    image: registry:2
    container_name: registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/cert.pem
      - REGISTRY_HTTP_TLS_KEY=/certs/privkey.pem
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - ./nginx/ssl:/certs
    networks:
      - auth_net

networks:
  auth_net:
    driver: bridge