name: simlab-app

include:
  - ./infrastructure.yaml

services:
  backend:
    build: ./webapp/backend
    container_name: backend
    env_file:
      - ./webapp/backend/.env
    ports:
      - "5005:5005"
    volumes:
      - ./connectors:/connectors
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./registry/simlab-447518-3117f021d7b5.json:/registry/simlab-447518-3117f021d7b5.json
    depends_on:
      - mongo
    networks:
      - simlab_net

  frontend:
    build: ./webapp/frontend
    container_name: frontend
    env_file:
      - ./webapp/frontend/.env
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - simlab_net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - simlab_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./build:/usr/share/doc/sphinx-doc/
    depends_on:
      - backend
      - frontend
    networks:
      - simlab_net
