name: simlab-app

include:
  - ./infrastructure.yaml

services:
  backend:
    build: ./webapp/backend
    container_name: backend
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5005
      - MONGO_URI=mongodb://admin:admin@mongo:27017
      - DOCKER_BASE_URL=unix:///var/run/docker.sock
      - DOCKER_REGISTRY_URI=https://localhost
      - DOCKER_REGISTRY_USER=admin
      - DOCKER_REGISTRY_PASSWORD=admin
      - JENKINS_URI=http://localhost:8080
      - JENKINS_USER=admin
      - JENKINS_PASSWORD=admin
    ports:
      - "5005:5005"
    volumes:
      - ./connectors:/connectors
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    depends_on:
      - mongo
    networks:
      - simlab_net

  frontend:
    build: ./webapp/frontend
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - simlab_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./build:/usr/share/doc/sphinx-doc/
    depends_on:
      - backend
      - frontend
      - registry
    networks:
      - simlab_net
