name: "Build and Test Python Code"
description: "Build and test Python code."

inputs:
  code_dir:
    description: "The directory containing the Python code."
    required: true
  test_dir:
    description: "The directory containing the Python tests."
    required: true
  artifact_prefix:
    description: "Prefix for the artifact names."
    required: true
    default: "coverage"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        cache: "pip"

    - name: Install Dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r ${{ inputs.code_dir }}/requirements.txt
        pip install pytest-github-actions-annotate-failures

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: "6.0"

    - name: Start Docker Registry
      shell: bash
      run: |
        docker run -d -p 5000:5000 --name registry registry:2

    - name: Wait for Docker Registry
      shell: bash
      run: |
        while ! curl -s http://localhost:5000/v2/; do sleep 1; done

    - name: PyTest with code coverage
      shell: bash
      # continue-on-error: true
      run: |
        pytest --junitxml pytest.xml --cov=${{ inputs.code_dir }} --cov-report=term-missing --cov-report=xml --cov-branch ${{ inputs.test_dir }} | tee pytest-coverage.txt

    - name: Stop and Remove Docker Registry
      shell: bash
      run: |
        docker stop registry || true
        docker rm registry || true

    - name: Upload Coverage Results txt
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_prefix }}-coverage-results-txt
        path: ./pytest-coverage.txt

    - name: Upload Coverage Results xml
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_prefix }}-coverage-results-xml
        path: ./coverage.xml

    - name: Upload Unit Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_prefix }}-unit-test-py39
        path: ./pytest.xml
  