name: "CI Webapp Backend"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "webapp/backend/**"
      - "tests/backend/**"

jobs:
  pre-commit:
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Run Pre-commit Checks
        uses: ./.github/actions/pre_commit
        with:
          code_dir: "webapp/backend"
          test_dir: "tests/backend"

  build-and-test:
    name: "Build and Test Python 3.9"
    runs-on: ubuntu-latest
    if: always()
    timeout-minutes: 20

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: "6.0"

      - name: Build and Test Python Code
        uses: ./.github/actions/build_test
        with:
          code_dir: "webapp/backend"
          test_dir: "tests/backend"

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: build-and-test
    runs-on: ubuntu-latest
    if: always()
    timeout-minutes: 20

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/unit-test-py39/*.xml

      - name: Publish Coverage Results
        uses: MishaKav/pytest-coverage-comment@main
        with:
          default-branch: main
          pytest-coverage-path: artifacts/coverage-results-txt/pytest-coverage.txt
          title: Backend Coverage Report
          badge-title: Coverage
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
