name: "CI Merge to Main"

on:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: "Run Pre-commit Checks"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Pre-commit Checks Backend
        uses: ./.github/actions/pre_commit
        with:
          code_dir: "webapp/backend"
          test_dir: "tests/backend"

      - name: Run Pre-commit Checks SimLab
        uses: ./.github/actions/pre_commit
        with:
          code_dir: "simlab"
          test_dir: "tests/simlab"

  build-and-test-backend:
    name: "Build and Test Backend"
    runs-on: ubuntu-latest
    needs: pre-commit
    timeout-minutes: 20

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: "6.0"

      - name: Build and Test Python Code
        uses: ./.github/actions/build_test
        with:
          code_dir: "webapp/backend"
          test_dir: "tests/backend"
          artifact_prefix: "backend"

  build-and-test-simlab:
    name: "Build and Test SimLab"
    runs-on: ubuntu-latest
    needs: pre-commit
    timeout-minutes: 20

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Test Python Code
        uses: ./.github/actions/build_test
        with:
          code_dir: "simlab"
          test_dir: "tests/simlab"
          artifact_prefix: "simlab"

  update-coverage-badges:
    name: "Update Coverage Badges in README"
    runs-on: ubuntu-latest
    needs: [build-and-test-backend, build-and-test-simlab]
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Backend Coverage Results
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage-results-txt
          path: artifacts/backend_coverage
      
      - name: Download SimLab Coverage Results
        uses: actions/download-artifact@v4
        with:
          name: simlab-coverage-results-txt
          path: artifacts/simlab_coverage

      - name: Update Coverage Backend Badge
        uses: ./.github/actions/coverage_badge
        with:
          coverage_file: "artifacts/backend_coverage/pytest-coverage.txt"
          badge_title: "backend"

      - name: Update Coverage SimLab Badge
        uses: ./.github/actions/coverage_badge
        with:
          coverage_file: "artifacts/simlab_coverage/pytest-coverage.txt"
          badge_title: "simlab"

      - name: Commit Updated README.md
        shell: bash
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update coverage badge in README"
          git push 
