name: "CI Merge to Main"

on:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: "Run Pre-commit Checks"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Pre-commit Checks Backend
        uses: ./.github/actions/pre_commit
        with:
          code_dir: "webapp/backend"
          test_dir: "tests/backend"

      - name: Run Pre-commit Checks SimLab
        uses: ./.github/actions/pre_commit
        with:
          code_dir: "simlab"
          test_dir: "tests/simlab"

  build-and-test-backend:
    name: "Build and Test Backend"
    runs-on: ubuntu-latest
    needs: pre-commit
    timeout-minutes: 20

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: "6.0"

      - name: Build and Test Python Code
        uses: ./.github/actions/build_test
        with:
          code_dir: "webapp/backend"
          test_dir: "tests/backend"

      - name: Update coverage badge in README
        uses: ./.github/actions/coverage_badge
        with:
          coverage_file: "artifacts/coverage-results-txt/pytest-coverage.txt"
          badge_title: "backend"

  build-and-test-simlab:
    name: "Build and Test SimLab"
    runs-on: ubuntu-latest
    needs: pre-commit
    timeout-minutes: 20

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Test Python Code
        uses: ./.github/actions/build_test
        with:
          code_dir: "simlab"
          test_dir: "tests/simlab"

      - name: Update coverage badge in README
        uses: ./.github/actions/coverage_badge
        with:
          coverage_file: "artifacts/coverage-results-txt/pytest-coverage.txt"
          badge_title: "simlab"
